spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/balance}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Riy@kum@ri08}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CORS config
cors.allowedOrigins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# JWT Config (256-bit secret key)
jwt.secret=${JWT_SECRET:94a08da1bf9c3a3c20078b5cecc2113ae87bb4a8d43add22d64f0ea6b54131df}
jwt.expiration=86400000

# Tesseract Config (assuming standard Windows install path)
tesseract.datapath=${TESSERACT_DATAPATH:C:/Program Files/Tesseract-OCR/tessdata}
